version: '3'
services:
  dokuwiki:
    container_name: dokuwiki
    image: php:7-apache-bullseye
    restart: unless-stopped
    networks:
      - dokuwiki
    ports:
      - '9090:80'
    volumes:
      - '.:/var/www/html'

networks:
  dokuwiki:

volumes:
  dokuwiki_config:
    driver: local
