# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 10 Aug 2021 02:09:40 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

logix01001:$2y$10$HsuXB2ubhUIlTrP0zKA8seVjbZ6svAu5aANZCD6c45fyxT5P0x2Yi:Jerome:jeromedelrosario01001@gmail.com:admin,user
